# Site settings
title: Samuel's Blog
header-img: img/home-bg.jpg
email: xuzhou@gmail.com
description: "You are reading my blog "
baseurl: ""
url: "http://hellosilence.github.io"

# SNS settings
RSS: false

github_username:  hellosilence
weibo_username: enjoycodeme
zhihu_username: hellosilence

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Markdown settings
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible, so I switch to kramdown
# markdown: kramdown

# document: http://jekyllrb.com/docs/configuration/#kramdown
# use Github Flavored Markdown !important
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  hard_wrap: false
# Duoshuo settings
 # Please set your own DuoShuo account.

useShare: true      # use Comment only. seeing the Share component is depend on Comment so we can NOT use share only.
# Todo: Analysis settings
# Please set your own analysis account
#useBaiduAnalysis: true
useGoogleAnalysis: true
gems: [jekyll-paginate]
